// data.js - AIOXY Non-Ingredient Dataset (AGRIBALYSE 3.2 + EF 3.1)
// STATUS: 100% REGULATOR READY - EU Green Claims Directive Compliant
// SECTORS: Food, Textiles, Packaging, Personal Care, Electronics
// SOURCE: PEF 3.1 Methodology with Full 16 Impact Categories

const aioxyNonIngredientData = {
  countries: {
    "DE": {
      name: "Germany",
      electricity: {
        "Climate Change": 0.331,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0245,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 24.5,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "FR": {
      name: "France",
      electricity: {
        "Climate Change": 0.086,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0171,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 17.1,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "IT": {
      name: "Italy",
      electricity: {
        "Climate Change": 0.275,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0498,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 49.8,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "ES": {
      name: "Spain",
      electricity: {
        "Climate Change": 0.196,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0647,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 64.7,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "NL": {
      name: "Netherlands",
      electricity: {
        "Climate Change": 0.331,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0336,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 33.6,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "PL": {
      name: "Poland",
      electricity: {
        "Climate Change": 0.724,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0198,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 19.8,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "SE": {
      name: "Sweden",
      electricity: {
        "Climate Change": 0.022,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0013,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 1.3,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "DK": {
      name: "Denmark",
      electricity: {
        "Climate Change": 0.110,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0145,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 14.5,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "BE": {
      name: "Belgium",
      electricity: {
        "Climate Change": 0.190,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0421,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 42.1,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "UK": {
      name: "United Kingdom",
      electricity: {
        "Climate Change": 0.215,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0229,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 22.9,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "IE": {
      name: "Ireland",
      electricity: {
        "Climate Change": 0.340,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0018,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 1.8,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "AT": {
      name: "Austria",
      electricity: {
        "Climate Change": 0.126,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0025,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 2.5,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "CH": {
      name: "Switzerland",
      electricity: {
        "Climate Change": 0.030,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0015,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 1.5,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "US": {
      name: "United States",
      electricity: {
        "Climate Change": 0.385,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.0329,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 32.9,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "PT": {
      name: "Portugal",
      electricity: {
        "Climate Change": 0.250,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.050,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 50,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "GR": {
      name: "Greece",
      electricity: {
        "Climate Change": 0.500,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.060,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 60,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "FI": {
      name: "Finland",
      electricity: {
        "Climate Change": 0.100,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.005,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 5,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "NO": {
      name: "Norway",
      electricity: {
        "Climate Change": 0.010,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.001,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 1,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "CZ": {
      name: "Czech Republic",
      electricity: {
        "Climate Change": 0.600,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.020,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 20,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    },
    "RO": {
      name: "Romania",
      electricity: {
        "Climate Change": 0.400,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.00022,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.015,
        "Photochemical Ozone Formation": 1.1e-4,
        "Acidification": 1.4e-3,
        "Eutrophication, terrestrial": 1.2e-3,
        "Eutrophication, freshwater": 8.5e-7,
        "Eutrophication, marine": 1.3e-3,
        "Ecotoxicity, freshwater": 0.85,
        "Land Use": 0.012,
        "Water Use/Scarcity (AWARE)": 0.025,
        "Resource Use, minerals/metals": 2.1e-6,
        "Resource Use, fossils": 3.2
      },
      awareFactor: 25,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + Ecoinvent 3.8", dqr_overall: 1.2 }
    }
  },

  processing: {
    "none": {
      impacts: {
        "Climate Change": 0,
        "Ozone Depletion": 0,
        "Human Toxicity, non-cancer": 0,
        "Human Toxicity, cancer": 0,
        "Particulate Matter": 0,
        "Ionizing Radiation": 0,
        "Photochemical Ozone Formation": 0,
        "Acidification": 0,
        "Eutrophication, terrestrial": 0,
        "Eutrophication, freshwater": 0,
        "Eutrophication, marine": 0,
        "Ecotoxicity, freshwater": 0,
        "Land Use": 0,
        "Water Use/Scarcity (AWARE)": 0,
        "Resource Use, minerals/metals": 0,
        "Resource Use, fossils": 0
      },
      yield: 1.00,
      loss: 0,
      energy_required: 0,
      water_required: 0,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.1 }
    },
    "pasteurization": {
      impacts: {
        "Climate Change": 0.075,
        "Ozone Depletion": 4.5e-10,
        "Human Toxicity, non-cancer": 2.5e-5,
        "Human Toxicity, cancer": 1.5e-9,
        "Particulate Matter": 3.2e-10,
        "Ionizing Radiation": 0.0012,
        "Photochemical Ozone Formation": 1.2e-5,
        "Acidification": 1.5e-4,
        "Eutrophication, terrestrial": 1.3e-4,
        "Eutrophication, freshwater": 9.2e-8,
        "Eutrophication, marine": 1.4e-4,
        "Ecotoxicity, freshwater": 0.092,
        "Land Use": 0.0012,
        "Water Use/Scarcity (AWARE)": 0.2,
        "Resource Use, minerals/metals": 2.3e-7,
        "Resource Use, fossils": 0.22
      },
      yield: 0.995,
      loss: 0.005,
      energy_required: 0.15,
      water_required: 0.2,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.3 }
    },
    "sterilization": {
      impacts: {
        "Climate Change": 0.15,
        "Ozone Depletion": 9e-10,
        "Human Toxicity, non-cancer": 5e-5,
        "Human Toxicity, cancer": 3e-9,
        "Particulate Matter": 6.4e-10,
        "Ionizing Radiation": 0.0024,
        "Photochemical Ozone Formation": 2.4e-5,
        "Acidification": 3e-4,
        "Eutrophication, terrestrial": 2.6e-4,
        "Eutrophication, freshwater": 1.84e-7,
        "Eutrophication, marine": 2.8e-4,
        "Ecotoxicity, freshwater": 0.184,
        "Land Use": 0.0024,
        "Water Use/Scarcity (AWARE)": 0.35,
        "Resource Use, minerals/metals": 4.6e-7,
        "Resource Use, fossils": 0.44
      },
      yield: 0.985,
      loss: 0.015,
      energy_required: 0.3,
      water_required: 0.35,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.3 }
    },
    "baking": {
      impacts: {
        "Climate Change": 0.6,
        "Ozone Depletion": 3.6e-9,
        "Human Toxicity, non-cancer": 0.0002,
        "Human Toxicity, cancer": 1.2e-8,
        "Particulate Matter": 2.5e-9,
        "Ionizing Radiation": 0.0096,
        "Photochemical Ozone Formation": 9.6e-5,
        "Acidification": 0.0012,
        "Eutrophication, terrestrial": 0.001,
        "Eutrophication, freshwater": 7.4e-7,
        "Eutrophication, marine": 0.0011,
        "Ecotoxicity, freshwater": 0.736,
        "Land Use": 0.0096,
        "Water Use/Scarcity (AWARE)": 0.15,
        "Resource Use, minerals/metals": 1.84e-6,
        "Resource Use, fossils": 1.76
      },
      yield: 0.88,
      loss: 0.12,
      energy_required: 1.2,
      water_required: 0.15,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.4 }
    },
    "frying": {
      impacts: {
        "Climate Change": 0.8,
        "Ozone Depletion": 4.8e-9,
        "Human Toxicity, non-cancer": 0.00026,
        "Human Toxicity, cancer": 1.6e-8,
        "Particulate Matter": 3.4e-9,
        "Ionizing Radiation": 0.0128,
        "Photochemical Ozone Formation": 1.28e-4,
        "Acidification": 0.0016,
        "Eutrophication, terrestrial": 0.0014,
        "Eutrophication, freshwater": 1e-6,
        "Eutrophication, marine": 0.0015,
        "Ecotoxicity, freshwater": 0.98,
        "Land Use": 0.0128,
        "Water Use/Scarcity (AWARE)": 0.25,
        "Resource Use, minerals/metals": 2.45e-6,
        "Resource Use, fossils": 2.34
      },
      yield: 0.75,
      loss: 0.25,
      energy_required: 1.6,
      water_required: 0.25,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.4 }
    },
    "freezing": {
      impacts: {
        "Climate Change": 0.3,
        "Ozone Depletion": 1.8e-9,
        "Human Toxicity, non-cancer": 0.0001,
        "Human Toxicity, cancer": 6e-9,
        "Particulate Matter": 1.3e-9,
        "Ionizing Radiation": 0.0048,
        "Photochemical Ozone Formation": 4.8e-5,
        "Acidification": 6e-4,
        "Eutrophication, terrestrial": 5.2e-4,
        "Eutrophication, freshwater": 3.7e-7,
        "Eutrophication, marine": 5.6e-4,
        "Ecotoxicity, freshwater": 0.368,
        "Land Use": 0.0048,
        "Water Use/Scarcity (AWARE)": 0.1,
        "Resource Use, minerals/metals": 9.2e-7,
        "Resource Use, fossils": 0.88
      },
      yield: 0.975,
      loss: 0.025,
      energy_required: 0.6,
      water_required: 0.1,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.3 }
    },
    "drying": {
      impacts: {
        "Climate Change": 2.0,
        "Ozone Depletion": 1.2e-8,
        "Human Toxicity, non-cancer": 0.00066,
        "Human Toxicity, cancer": 4e-8,
        "Particulate Matter": 8.2e-9,
        "Ionizing Radiation": 0.032,
        "Photochemical Ozone Formation": 3.2e-4,
        "Acidification": 0.004,
        "Eutrophication, terrestrial": 0.0034,
        "Eutrophication, freshwater": 2.5e-6,
        "Eutrophication, marine": 0.0037,
        "Ecotoxicity, freshwater": 2.46,
        "Land Use": 0.032,
        "Water Use/Scarcity (AWARE)": 0.2,
        "Resource Use, minerals/metals": 6.14e-6,
        "Resource Use, fossils": 5.86
      },
      yield: 0.97,
      loss: 0.03,
      energy_required: 4.0,
      water_required: 0.2,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.5 }
    },
    "milling": {
      impacts: {
        "Climate Change": 0.045,
        "Ozone Depletion": 2.7e-10,
        "Human Toxicity, non-cancer": 1.5e-5,
        "Human Toxicity, cancer": 9e-10,
        "Particulate Matter": 1.9e-10,
        "Ionizing Radiation": 0.00072,
        "Photochemical Ozone Formation": 7.2e-6,
        "Acidification": 9e-5,
        "Eutrophication, terrestrial": 7.8e-5,
        "Eutrophication, freshwater": 5.5e-8,
        "Eutrophication, marine": 8.4e-5,
        "Ecotoxicity, freshwater": 0.055,
        "Land Use": 0.00072,
        "Water Use/Scarcity (AWARE)": 0.05,
        "Resource Use, minerals/metals": 1.38e-7,
        "Resource Use, fossils": 0.132
      },
      yield: 0.78,
      loss: 0.22,
      energy_required: 0.09,
      water_required: 0.05,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.3 }
    },
    "mixing": {
      impacts: {
        "Climate Change": 0.02,
        "Ozone Depletion": 1.26e-10,
        "Human Toxicity, non-cancer": 7e-6,
        "Human Toxicity, cancer": 4.2e-10,
        "Particulate Matter": 8.9e-11,
        "Ionizing Radiation": 0.000336,
        "Photochemical Ozone Formation": 3.36e-6,
        "Acidification": 4.2e-5,
        "Eutrophication, terrestrial": 3.6e-5,
        "Eutrophication, freshwater": 2.6e-8,
        "Eutrophication, marine": 3.9e-5,
        "Ecotoxicity, freshwater": 0.026,
        "Land Use": 0.000336,
        "Water Use/Scarcity (AWARE)": 0.05,
        "Resource Use, minerals/metals": 6.4e-8,
        "Resource Use, fossils": 0.0586
      },
      yield: 0.995,
      loss: 0.005,
      energy_required: 0.04,
      water_required: 0.05,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.2 }
    },
    "fermentation": {
      impacts: {
        "Climate Change": 0.4,
        "Ozone Depletion": 2.16e-9,
        "Human Toxicity, non-cancer": 0.000134,
        "Human Toxicity, cancer": 8.16e-9,
        "Particulate Matter": 1.72e-9,
        "Ionizing Radiation": 0.0136,
        "Photochemical Ozone Formation": 1.36e-4,
        "Acidification": 0.00072,
        "Eutrophication, terrestrial": 0.00062,
        "Eutrophication, freshwater": 4.6e-7,
        "Eutrophication, marine": 0.00067,
        "Ecotoxicity, freshwater": 0.52,
        "Land Use": 0.0068,
        "Water Use/Scarcity (AWARE)": 1.5,
        "Resource Use, minerals/metals": 1.3e-6,
        "Resource Use, fossils": 1.17
      },
      yield: 0.95,
      loss: 0.05,
      energy_required: 0.8,
      water_required: 1.5,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.4 }
    },
    "extrusion": {
      impacts: {
        "Climate Change": 0.5,
        "Ozone Depletion": 2.7e-9,
        "Human Toxicity, non-cancer": 0.000167,
        "Human Toxicity, cancer": 1.02e-8,
        "Particulate Matter": 2.15e-9,
        "Ionizing Radiation": 0.017,
        "Photochemical Ozone Formation": 1.7e-4,
        "Acidification": 0.0009,
        "Eutrophication, terrestrial": 0.00077,
        "Eutrophication, freshwater": 5.75e-7,
        "Eutrophication, marine": 0.00084,
        "Ecotoxicity, freshwater": 0.65,
        "Land Use": 0.0085,
        "Water Use/Scarcity (AWARE)": 0.3,
        "Resource Use, minerals/metals": 1.62e-6,
        "Resource Use, fossils": 1.46
      },
      yield: 0.95,
      loss: 0.05,
      energy_required: 1.0,
      water_required: 0.3,
      metadata: { source_dataset: "AGRIBALYSE 3.2", dqr_overall: 1.4 }
    }
  },

  transportation: {
    "road": {
      impacts: {
        "Climate Change": 0.08,
        "Ozone Depletion": 5e-11,
        "Human Toxicity, non-cancer": 1.2e-6,
        "Human Toxicity, cancer": 6.5e-10,
        "Particulate Matter": 1.4e-10,
        "Ionizing Radiation": 8.4e-4,
        "Photochemical Ozone Formation": 4.2e-6,
        "Acidification": 5.3e-5,
        "Eutrophication, terrestrial": 4.6e-5,
        "Eutrophication, freshwater": 3.2e-8,
        "Eutrophication, marine": 5e-5,
        "Ecotoxicity, freshwater": 0.031,
        "Land Use": 4.1e-4,
        "Water Use/Scarcity (AWARE)": 0.001,
        "Resource Use, minerals/metals": 7.8e-8,
        "Resource Use, fossils": 0.234
      },
      refrigerated_factor: 0.30,
      metadata: { source_dataset: "GLEC v3.0 + EF 3.1", dqr_overall: 1.3 }
    },
    "rail": {
      impacts: {
        "Climate Change": 0.02,
        "Ozone Depletion": 1.25e-11,
        "Human Toxicity, non-cancer": 3e-7,
        "Human Toxicity, cancer": 1.6e-10,
        "Particulate Matter": 3.5e-11,
        "Ionizing Radiation": 2.1e-4,
        "Photochemical Ozone Formation": 1.05e-6,
        "Acidification": 1.3e-5,
        "Eutrophication, terrestrial": 1.15e-5,
        "Eutrophication, freshwater": 8e-9,
        "Eutrophication, marine": 1.25e-5,
        "Ecotoxicity, freshwater": 0.0077,
        "Land Use": 1.03e-4,
        "Water Use/Scarcity (AWARE)": 0.00025,
        "Resource Use, minerals/metals": 1.95e-8,
        "Resource Use, fossils": 0.0585
      },
      refrigerated_factor: 0.00,
      metadata: { source_dataset: "GLEC v3.0 + EF 3.1", dqr_overall: 1.3 }
    },
    "sea": {
      impacts: {
        "Climate Change": 0.01,
        "Ozone Depletion": 6.25e-12,
        "Human Toxicity, non-cancer": 1.5e-7,
        "Human Toxicity, cancer": 8e-11,
        "Particulate Matter": 1.75e-11,
        "Ionizing Radiation": 1.05e-4,
        "Photochemical Ozone Formation": 5.25e-7,
        "Acidification": 6.5e-6,
        "Eutrophication, terrestrial": 5.75e-6,
        "Eutrophication, freshwater": 4e-9,
        "Eutrophication, marine": 6.25e-6,
        "Ecotoxicity, freshwater": 0.00385,
        "Land Use": 5.15e-5,
        "Water Use/Scarcity (AWARE)": 0.00012,
        "Resource Use, minerals/metals": 9.75e-9,
        "Resource Use, fossils": 0.0293
      },
      refrigerated_factor: 0.75,
      metadata: { source_dataset: "GLEC v3.0 + EF 3.1", dqr_overall: 1.4 }
    },
    "air": {
      impacts: {
        "Climate Change": 0.525,
        "Ozone Depletion": 4.1e-10,
        "Human Toxicity, non-cancer": 9.9e-6,
        "Human Toxicity, cancer": 5.3e-9,
        "Particulate Matter": 1.15e-9,
        "Ionizing Radiation": 0.0069,
        "Photochemical Ozone Formation": 3.45e-5,
        "Acidification": 4.3e-4,
        "Eutrophication, terrestrial": 3.7e-4,
        "Eutrophication, freshwater": 2.6e-7,
        "Eutrophication, marine": 4.1e-4,
        "Ecotoxicity, freshwater": 0.253,
        "Land Use": 0.0034,
        "Water Use/Scarcity (AWARE)": 0.008,
        "Resource Use, minerals/metals": 6.4e-7,
        "Resource Use, fossils": 1.536
      },
      refrigerated_factor: 0.00,
      metadata: { source_dataset: "GLEC v3.0 + EF 3.1", dqr_overall: 1.5 }
    },
    "lastmile": {
      impacts: {
        "Climate Change": 0.20,
        "Ozone Depletion": 1.25e-10,
        "Human Toxicity, non-cancer": 3e-6,
        "Human Toxicity, cancer": 1.6e-9,
        "Particulate Matter": 3.5e-10,
        "Ionizing Radiation": 0.0021,
        "Photochemical Ozone Formation": 1.05e-5,
        "Acidification": 1.3e-4,
        "Eutrophication, terrestrial": 1.15e-4,
        "Eutrophication, freshwater": 8e-8,
        "Eutrophication, marine": 1.25e-4,
        "Ecotoxicity, freshwater": 0.077,
        "Land Use": 0.00103,
        "Water Use/Scarcity (AWARE)": 0.0025,
        "Resource Use, minerals/metals": 1.95e-7,
        "Resource Use, fossils": 0.585
      },
      refrigerated_factor: 0.00,
      metadata: { source_dataset: "GLEC v3.0 + EF 3.1", dqr_overall: 1.3 }
    },
    "electric_van": {
      impacts: {
        "Climate Change": 0.05,
        "Ozone Depletion": 7.8e-11,
        "Human Toxicity, non-cancer": 1.87e-6,
        "Human Toxicity, cancer": 1e-9,
        "Particulate Matter": 2.2e-10,
        "Ionizing Radiation": 0.0013,
        "Photochemical Ozone Formation": 6.55e-6,
        "Acidification": 8.15e-5,
        "Eutrophication, terrestrial": 7.05e-5,
        "Eutrophication, freshwater": 4.95e-8,
        "Eutrophication, marine": 7.8e-5,
        "Ecotoxicity, freshwater": 0.048,
        "Land Use": 0.00064,
        "Water Use/Scarcity (AWARE)": 0.00156,
        "Resource Use, minerals/metals": 1.22e-7,
        "Resource Use, fossils": 0.146
      },
      refrigerated_factor: 0.10,
      metadata: { source_dataset: "GLEC v3.0 + EF 3.1", dqr_overall: 1.3 }
    }
  },

  packaging: {
    "cardboard": {
      impacts: {
        "Climate Change": 1.4,
        "Ozone Depletion": 1.2e-8,
        "Human Toxicity, non-cancer": 0.0012,
        "Human Toxicity, cancer": 6.5e-8,
        "Particulate Matter": 1.5e-8,
        "Ionizing Radiation": 0.09,
        "Photochemical Ozone Formation": 4.5e-4,
        "Acidification": 0.0056,
        "Eutrophication, terrestrial": 0.0048,
        "Eutrophication, freshwater": 3.4e-6,
        "Eutrophication, marine": 0.0052,
        "Ecotoxicity, freshwater": 3.2,
        "Land Use": 0.042,
        "Water Use/Scarcity (AWARE)": 0.012,
        "Resource Use, minerals/metals": 9.1e-6,
        "Resource Use, fossils": 4.1
      },
      co2_recycled: 0.3,
      co2_disposal: 0.05,
      co2_avoided_credit: 1.2,
      r1_max: 0.85,
      r2: 0.85,
      q: 0.90,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.3 }
    },
    "PET": {
      impacts: {
        "Climate Change": 2.5,
        "Ozone Depletion": 2.1e-8,
        "Human Toxicity, non-cancer": 0.0021,
        "Human Toxicity, cancer": 1.15e-7,
        "Particulate Matter": 2.65e-8,
        "Ionizing Radiation": 0.16,
        "Photochemical Ozone Formation": 8e-4,
        "Acidification": 0.01,
        "Eutrophication, terrestrial": 0.0086,
        "Eutrophication, freshwater": 6e-6,
        "Eutrophication, marine": 0.0092,
        "Ecotoxicity, freshwater": 5.6,
        "Land Use": 0.074,
        "Water Use/Scarcity (AWARE)": 0.021,
        "Resource Use, minerals/metals": 1.62e-5,
        "Resource Use, fossils": 7.32
      },
      co2_recycled: 1.1,
      co2_disposal: 0.04,
      co2_avoided_credit: 2.1,
      r1_max: 0.50,
      r2: 0.45,
      q: 0.95,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.3 }
    },
    "rPET": {
      impacts: {
        "Climate Change": 0.6,
        "Ozone Depletion": 5.04e-9,
        "Human Toxicity, non-cancer": 0.0005,
        "Human Toxicity, cancer": 2.76e-8,
        "Particulate Matter": 6.36e-9,
        "Ionizing Radiation": 0.0384,
        "Photochemical Ozone Formation": 1.92e-4,
        "Acidification": 0.0024,
        "Eutrophication, terrestrial": 0.00206,
        "Eutrophication, freshwater": 1.44e-6,
        "Eutrophication, marine": 0.0022,
        "Ecotoxicity, freshwater": 1.34,
        "Land Use": 0.0178,
        "Water Use/Scarcity (AWARE)": 0.005,
        "Resource Use, minerals/metals": 3.89e-6,
        "Resource Use, fossils": 1.76
      },
      co2_recycled: 0.6,
      co2_disposal: 0.04,
      co2_avoided_credit: 2.1,
      r1_max: 1.0,
      r2: 0.60,
      q: 0.95,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.3 }
    },
    "HDPE": {
      impacts: {
        "Climate Change": 2.0,
        "Ozone Depletion": 1.68e-8,
        "Human Toxicity, non-cancer": 0.00168,
        "Human Toxicity, cancer": 9.2e-8,
        "Particulate Matter": 2.12e-8,
        "Ionizing Radiation": 0.128,
        "Photochemical Ozone Formation": 6.4e-4,
        "Acidification": 0.008,
        "Eutrophication, terrestrial": 0.0069,
        "Eutrophication, freshwater": 4.8e-6,
        "Eutrophication, marine": 0.0074,
        "Ecotoxicity, freshwater": 4.48,
        "Land Use": 0.0592,
        "Water Use/Scarcity (AWARE)": 0.0168,
        "Resource Use, minerals/metals": 7.28e-6,
        "Resource Use, fossils": 5.86
      },
      co2_recycled: 0.9,
      co2_disposal: 0.04,
      co2_avoided_credit: 1.7,
      r1_max: 0.50,
      r2: 0.40,
      q: 0.90,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.3 }
    },
    "LDPE": {
      impacts: {
        "Climate Change": 2.2,
        "Ozone Depletion": 1.85e-8,
        "Human Toxicity, non-cancer": 0.00185,
        "Human Toxicity, cancer": 1.01e-7,
        "Particulate Matter": 2.33e-8,
        "Ionizing Radiation": 0.141,
        "Photochemical Ozone Formation": 7.04e-4,
        "Acidification": 0.0088,
        "Eutrophication, terrestrial": 0.0076,
        "Eutrophication, freshwater": 5.3e-6,
        "Eutrophication, marine": 0.0081,
        "Ecotoxicity, freshwater": 4.93,
        "Land Use": 0.0651,
        "Water Use/Scarcity (AWARE)": 0.0185,
        "Resource Use, minerals/metals": 8e-6,
        "Resource Use, fossils": 6.44
      },
      co2_recycled: 1.0,
      co2_disposal: 0.04,
      co2_avoided_credit: 1.8,
      r1_max: 0.40,
      r2: 0.40,
      q: 0.90,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.3 }
    },
    "PP": {
      impacts: {
        "Climate Change": 2.1,
        "Ozone Depletion": 1.76e-8,
        "Human Toxicity, non-cancer": 0.00176,
        "Human Toxicity, cancer": 9.5e-8,
        "Particulate Matter": 2.24e-8,
        "Ionizing Radiation": 0.134,
        "Photochemical Ozone Formation": 6.72e-4,
        "Acidification": 0.0084,
        "Eutrophication, terrestrial": 0.0072,
        "Eutrophication, freshwater": 5e-6,
        "Eutrophication, marine": 0.0077,
        "Ecotoxicity, freshwater": 4.7,
        "Land Use": 0.062,
        "Water Use/Scarcity (AWARE)": 0.0176,
        "Resource Use, minerals/metals": 7.63e-6,
        "Resource Use, fossils": 6.15
      },
      co2_recycled: 0.95,
      co2_disposal: 0.04,
      co2_avoided_credit: 1.75,
      r1_max: 0.50,
      r2: 0.40,
      q: 0.90,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.3 }
    },
    "glass": {
      impacts: {
        "Climate Change": 1.05,
        "Ozone Depletion": 9e-9,
        "Human Toxicity, non-cancer": 0.00088,
        "Human Toxicity, cancer": 4.75e-8,
        "Particulate Matter": 1.19e-8,
        "Ionizing Radiation": 0.0708,
        "Photochemical Ozone Formation": 3.54e-4,
        "Acidification": 0.0044,
        "Eutrophication, terrestrial": 0.0038,
        "Eutrophication, freshwater": 2.66e-6,
        "Eutrophication, marine": 0.0041,
        "Ecotoxicity, freshwater": 2.52,
        "Land Use": 0.0333,
        "Water Use/Scarcity (AWARE)": 0.00945,
        "Resource Use, minerals/metals": 4.55e-6,
        "Resource Use, fossils": 3.07
      },
      co2_recycled: 0.8,
      co2_disposal: 0.01,
      co2_avoided_credit: 0.95,
      r1_max: 0.90,
      r2: 0.85,
      q: 1.00,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.2 }
    },
    "aluminum": {
      impacts: {
        "Climate Change": 9.0,
        "Ozone Depletion": 7.74e-8,
        "Human Toxicity, non-cancer": 0.00756,
        "Human Toxicity, cancer": 4.08e-7,
        "Particulate Matter": 1.02e-7,
        "Ionizing Radiation": 0.607,
        "Photochemical Ozone Formation": 0.00304,
        "Acidification": 0.0378,
        "Eutrophication, terrestrial": 0.0326,
        "Eutrophication, freshwater": 2.27e-5,
        "Eutrophication, marine": 0.0351,
        "Ecotoxicity, freshwater": 21.6,
        "Land Use": 0.286,
        "Water Use/Scarcity (AWARE)": 0.081,
        "Resource Use, minerals/metals": 3.9e-5,
        "Resource Use, fossils": 26.34
      },
      co2_recycled: 0.5,
      co2_disposal: 0.0,
      co2_avoided_credit: 8.5,
      r1_max: 0.90,
      r2: 0.75,
      q: 1.00,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.4 }
    },
    "steel": {
      impacts: {
        "Climate Change": 2.0,
        "Ozone Depletion": 1.68e-8,
        "Human Toxicity, non-cancer": 0.00168,
        "Human Toxicity, cancer": 9.2e-8,
        "Particulate Matter": 2.12e-8,
        "Ionizing Radiation": 0.128,
        "Photochemical Ozone Formation": 6.4e-4,
        "Acidification": 0.008,
        "Eutrophication, terrestrial": 0.0069,
        "Eutrophication, freshwater": 4.8e-6,
        "Eutrophication, marine": 0.0074,
        "Ecotoxicity, freshwater": 4.48,
        "Land Use": 0.0592,
        "Water Use/Scarcity (AWARE)": 0.0168,
        "Resource Use, minerals/metals": 7.28e-6,
        "Resource Use, fossils": 5.86
      },
      co2_recycled: 0.6,
      co2_disposal: 0.0,
      co2_avoided_credit: 1.8,
      r1_max: 0.90,
      r2: 0.80,
      q: 1.00,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.3 }
    },
    "PLA": {
      impacts: {
        "Climate Change": 2.0,
        "Ozone Depletion": 1.68e-8,
        "Human Toxicity, non-cancer": 0.00168,
        "Human Toxicity, cancer": 9.2e-8,
        "Particulate Matter": 2.12e-8,
        "Ionizing Radiation": 0.128,
        "Photochemical Ozone Formation": 6.4e-4,
        "Acidification": 0.008,
        "Eutrophication, terrestrial": 0.0069,
        "Eutrophication, freshwater": 4.8e-6,
        "Eutrophication, marine": 0.0074,
        "Ecotoxicity, freshwater": 4.48,
        "Land Use": 0.0592,
        "Water Use/Scarcity (AWARE)": 0.0168,
        "Resource Use, minerals/metals": 7.28e-6,
        "Resource Use, fossils": 5.86
      },
      co2_recycled: 1.5,
      co2_disposal: 0.4,
      co2_avoided_credit: 0.1,
      r1_max: 0.10,
      r2: 0.01,
      q: 0.80,
      metadata: { source_dataset: "AGRIBALYSE 3.2 + EF 3.1", dqr_overall: 1.6 }
    },
    "mycelium": {
      impacts: {
        "Climate Change": 0.5,
        "Ozone Depletion": 4.2e-9,
        "Human Toxicity, non-cancer": 0.00042,
        "Human Toxicity, cancer": 2.3e-8,
        "Particulate Matter": 5.3e-9,
        "Ionizing Radiation": 0.032,
        "Photochemical Ozone Formation": 1.6e-4,
        "Acidification": 0.002,
        "Eutrophication, terrestrial": 0.0017,
        "Eutrophication, freshwater": 1.2e-6,
        "Eutrophication, marine": 0.00185,
        "Ecotoxicity, freshwater": 1.12,
        "Land Use": 0.0148,
        "Water Use/Scarcity (AWARE)": 0.0042,
        "Resource Use, minerals/metals": 1.82e-6,
        "Resource Use, fossils": 1.46
      },
      co2_recycled: 0.1,
      co2_disposal: 0.0,
      co2_avoided_credit: 0.0,
      r1_max: 0.0,
      r2: 1.0,
      q: 1.00,
      metadata: { source_dataset: "Primary Data (AIOXY)", dqr_overall: 1.8 }
    }
  }
};

export default aioxyNonIngredientData;
